# Kotlin's official code style for formatting
kotlin.code.style=official

# Kotlin compiler daemon
kotlin.daemon.jvmargs=-Xmx8G

#Gradle JVM memory
org.gradle.jvmargs=-Xmx8G -Dfile.encoding=UTF-8

# Run independent projects/tasks in parallel
org.gradle.parallel=true

# Reuse outputs from previous builds
org.gradle.caching=true

# Cache Gradle configuration (Avoid repeating configuration work)
org.gradle.configuration-cache=true

# Keep Gradle daemon alive between builds
#org.gradle.daemon=true

# More efficient file-change detection
#org.gradle.vfs.watch=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true