# Kotlin's official code style for formatting
kotlin.code.style=official

# Kotlin compiler daemon
kotlin.daemon.jvmargs=-Xmx2g

#Gradle JVM memory
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8

# Run independent projects/tasks in parallel
org.gradle.parallel=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

# Reuse outputs from previous builds
org.gradle.caching=true

# Cache Gradle configuration (Avoid repeating configuration work)
#org.gradle.configuration-cache=true
#org.gradle.configuration-cache.parallel=true

# Keep Gradle daemon alive between builds
#org.gradle.daemon=true

# More efficient file-change detection
#org.gradle.vfs.watch=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true


 systemProp.http.proxyHost=10.57.136.148
 systemProp.http.proxyPort=10809
 systemProp.https.proxyHost=10.57.136.148
 systemProp.https.proxyPort=10809