package ir.ornix.passgen.core.domain

/**
 * Provides HMAC-SHA512 signing using Master-Key-Digests (MKDs) stored in a secure key-management
 * environment.
 *
 * Implementations are expected to store MKDs in a secure environment, such as Android Keystore
 * with TEE or StrongBox hardware backing when available. The MKD should not be exposed to
 * application memory during signing operations.
 *
 * An **MKD (Master-Key-Digest)** is derived from the original **MK (Master Key)** by computing
 * its SHA-512 digest. The resulting 64-byte digest is registered and used as the HMAC-SHA512 key.
 *
 * Therefore, this interface computes:
 *
 *     rawMasterKeyDigest = SHA-512(rawMasterKey)
 *
 *     PasswordSeed = HMAC-SHA512(key = rawMasterKeyDigest, message = UTF-8(input))
 *
 * rather than:
 *
 *     HMAC-SHA512(key = rawMasterKey, message = UTF-8(input))
 *
 * This SHA-512 derivation is part of the contract of this interface. Any system that needs to
 * reproduce or verify a Password Seed generated by this signer must derive the same MKD from the
 * original Master Key before performing HMAC-SHA512.
 *
 * Implementations are responsible for minimizing the lifetime of sensitive material in application
 * memory. In particular, [rawMasterKey] and the derived MKD should not be retained after
 * [registerKey] completes and should be cleared from mutable memory when technically possible.
 *
 * Security requirements:
 *
 * - Use the most secure platform-native key storage available, preferably hardware-backed.
 * - Keep the MKD isolated from application memory whenever possible.
 * - Never persist or log the original Master Key (MK).
 * - Derive the MKD using the most secure native cryptographic implementation available.
 * - Minimize sensitive data lifetime and unnecessary memory copies; clear mutable buffers when possible.
 * - Perform HMAC operations inside the secure cryptographic facility whenever supported.
 * - Do not implement custom cryptography when a secure platform primitive is available.
 */
interface HmacSigner {

    /**
     * Registers a Master-Key-Digest (MKD) derived from [rawMasterKey].
     *
     * The supplied [rawMasterKey] is hashed using SHA-512. The resulting 64-byte digest becomes
     * the MKD and is registered as the HMAC-SHA512 key. The original [rawMasterKey] is not
     * registered as the signing key.
     *
     * Registering an MKD with an existing [mkdId] replaces the previously registered MKD.
     *
     * Implementations should clear sensitive intermediate data, including [rawMasterKey] and the
     * derived MKD, from mutable memory as soon as they are no longer required.
     *
     * @param mkdId identifier used to reference the registered MKD.
     * @param rawMasterKey original Master-Key bytes from which the MKD is derived.
     */
    suspend fun registerKey(mkdId: String, rawMasterKey: ByteArray)

    /**
     * Computes a Password Seed for [input] using the Master-Key-Digest registered under [mkdId].
     *
     * The **Password Seed** is the 64-byte HMAC-SHA512 MAC produced using the registered MKD as the
     * HMAC key:
     *
     *     rawMasterKeyDigest = SHA-512(rawMasterKey)
     *
     *     PasswordSeed = HMAC-SHA512(key = rawMasterKeyDigest, message = UTF-8(input))
     *
     * @param mkdId identifier of a previously registered MKD.
     * @param input message to authenticate. It is encoded as UTF-8 before signing.
     * @return the 64-byte Password Seed, which is the resulting HMAC-SHA512 MAC.
     * @throws SigningKeyNotFoundException if no MKD is registered under [mkdId].
     */
    suspend fun sign(mkdId: String, input: String): ByteArray

    /**
     * Checks whether a Master-Key-Digest (MKD) is registered under [mkdId].
     *
     * @param mkdId identifier of the MKD to check.
     * @return `true` if an MKD is registered under [mkdId]; `false` otherwise.
     */
    suspend fun hasMasterKeyDigest(mkdId: String): Boolean

    /**
     * Removes the Master-Key-Digest (MKD) registered under [mkdId].
     *
     * This operation is idempotent: if no MKD is registered under [mkdId], it has no effect.
     *
     * @param mkdId identifier of the MKD to remove.
     */
    suspend fun deleteMasterKeyDigest(mkdId: String)
}